
GET http://localhost:3000/routes

###
GET   http://localhost:3000/routes/64e84f8663409c3c17208b49

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "route riacho fundo",
    "source_id": "ChIJgVNdAMstWpMRFnbbHOKPKIY",
    "destination_id": "ChIJY_lQcsstWpMRYmeGc1nnMmQ"
}

### Coisas do mapa

### Pegar o place_id
GET http://localhost:3000/places?text=qs06 conjunto 1, riacho fundo 1, df


### Pegar direções entre dois pontos

GET http://localhost:3000/directions?originId=ChIJgVNdAMstWpMRFnbbHOKPKIY&destinationId=ChIJY_lQcsstWpMRYmeGc1nnMmQ