
GET http://localhost:3000/routes

###
GET   http://localhost:3000/routes/64e84f8663409c3c17208b49

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "route samambaia",
    "source_id": "ChIJrW982kgtWpMRZLYv2Tgx67w",
    "destination_id": "ChIJ1b4gOE8tWpMRArGuohgkBsU"
}

### Coisas do mapa

### Pegar o place_id
GET http://localhost:3000/places?text=betim, mg


### Pegar direções entre dois pontos

GET http://localhost:3000/directions?originId=ChIJm5DuIuMtWpMRl2N81a3__WY&destinationId=ChIJI-ijvEYtWpMRrICAZKkt0GI